/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSubmissionsRouteImport } from './routes/_authed/submissions'
import { Route as AuthedStudentRecordsRouteImport } from './routes/_authed/student-records'
import { Route as AuthedSubmissionsIndexRouteImport } from './routes/_authed/submissions.index'
import { Route as AuthedSubmissionsNewRouteImport } from './routes/_authed/submissions.new'
import { Route as AuthedSubmissionsSubmissionIdRouteImport } from './routes/_authed/submissions.$submissionId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSubmissionsRoute = AuthedSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudentRecordsRoute = AuthedStudentRecordsRouteImport.update({
  id: '/student-records',
  path: '/student-records',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSubmissionsIndexRoute = AuthedSubmissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSubmissionsRoute,
} as any)
const AuthedSubmissionsNewRoute = AuthedSubmissionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedSubmissionsRoute,
} as any)
const AuthedSubmissionsSubmissionIdRoute =
  AuthedSubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => AuthedSubmissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/student-records': typeof AuthedStudentRecordsRoute
  '/submissions': typeof AuthedSubmissionsRouteWithChildren
  '/submissions/$submissionId': typeof AuthedSubmissionsSubmissionIdRoute
  '/submissions/new': typeof AuthedSubmissionsNewRoute
  '/submissions/': typeof AuthedSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/student-records': typeof AuthedStudentRecordsRoute
  '/submissions/$submissionId': typeof AuthedSubmissionsSubmissionIdRoute
  '/submissions/new': typeof AuthedSubmissionsNewRoute
  '/submissions': typeof AuthedSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/student-records': typeof AuthedStudentRecordsRoute
  '/_authed/submissions': typeof AuthedSubmissionsRouteWithChildren
  '/_authed/submissions/$submissionId': typeof AuthedSubmissionsSubmissionIdRoute
  '/_authed/submissions/new': typeof AuthedSubmissionsNewRoute
  '/_authed/submissions/': typeof AuthedSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/student-records'
    | '/submissions'
    | '/submissions/$submissionId'
    | '/submissions/new'
    | '/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/student-records'
    | '/submissions/$submissionId'
    | '/submissions/new'
    | '/submissions'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/student-records'
    | '/_authed/submissions'
    | '/_authed/submissions/$submissionId'
    | '/_authed/submissions/new'
    | '/_authed/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/submissions': {
      id: '/_authed/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthedSubmissionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/student-records': {
      id: '/_authed/student-records'
      path: '/student-records'
      fullPath: '/student-records'
      preLoaderRoute: typeof AuthedStudentRecordsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/submissions/': {
      id: '/_authed/submissions/'
      path: '/'
      fullPath: '/submissions/'
      preLoaderRoute: typeof AuthedSubmissionsIndexRouteImport
      parentRoute: typeof AuthedSubmissionsRoute
    }
    '/_authed/submissions/new': {
      id: '/_authed/submissions/new'
      path: '/new'
      fullPath: '/submissions/new'
      preLoaderRoute: typeof AuthedSubmissionsNewRouteImport
      parentRoute: typeof AuthedSubmissionsRoute
    }
    '/_authed/submissions/$submissionId': {
      id: '/_authed/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/submissions/$submissionId'
      preLoaderRoute: typeof AuthedSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AuthedSubmissionsRoute
    }
  }
}

interface AuthedSubmissionsRouteChildren {
  AuthedSubmissionsSubmissionIdRoute: typeof AuthedSubmissionsSubmissionIdRoute
  AuthedSubmissionsNewRoute: typeof AuthedSubmissionsNewRoute
  AuthedSubmissionsIndexRoute: typeof AuthedSubmissionsIndexRoute
}

const AuthedSubmissionsRouteChildren: AuthedSubmissionsRouteChildren = {
  AuthedSubmissionsSubmissionIdRoute: AuthedSubmissionsSubmissionIdRoute,
  AuthedSubmissionsNewRoute: AuthedSubmissionsNewRoute,
  AuthedSubmissionsIndexRoute: AuthedSubmissionsIndexRoute,
}

const AuthedSubmissionsRouteWithChildren =
  AuthedSubmissionsRoute._addFileChildren(AuthedSubmissionsRouteChildren)

interface AuthedRouteChildren {
  AuthedStudentRecordsRoute: typeof AuthedStudentRecordsRoute
  AuthedSubmissionsRoute: typeof AuthedSubmissionsRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedStudentRecordsRoute: AuthedStudentRecordsRoute,
  AuthedSubmissionsRoute: AuthedSubmissionsRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
